// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"database/sql"
	"time"
)

type Message struct {
	ID       int64
	ServerID int64
	UserID   int64
	Content  string
	ReplyTo  sql.NullInt64
	IsReply  bool
	IsEdited bool
	Time     time.Time
}

type MessageReaction struct {
	MessageID int64
	UserID    int64
	Emoji     string
}

type Server struct {
	ID    int64
	Name  string
	Owner int64
}

type ServerInvite struct {
	ID        interface{}
	ServerID  int64
	UserID    int64
	ExpiresAt time.Time
}

type ServerMember struct {
	ServerID      int64
	UserID        int64
	IsBan         bool
	ServerDisplay sql.NullString
}

type User struct {
	ID           int64
	Username     string
	Display      string
	PasswordHash string
	JoinedAt     time.Time
	IsDeleted    bool
	CookieVer    int64
}
