// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"time"
)

type Message struct {
	ID       int64     `json:"id"`
	ServerID int64     `json:"server_id"`
	UserID   int64     `json:"user_id"`
	Content  string    `json:"content"`
	ReplyTo  *int64    `json:"reply_to"`
	IsReply  bool      `json:"is_reply"`
	IsEdited bool      `json:"is_edited"`
	Time     time.Time `json:"time"`
}

type MessageReaction struct {
	MessageID int64  `json:"message_id"`
	UserID    int64  `json:"user_id"`
	Emoji     string `json:"emoji"`
}

type Server struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Owner int64  `json:"owner"`
}

type ServerInvite struct {
	ID        interface{} `json:"id"`
	ServerID  int64       `json:"server_id"`
	UserID    int64       `json:"user_id"`
	ExpiresAt *time.Time  `json:"expires_at"`
}

type ServerMember struct {
	ServerID      int64   `json:"server_id"`
	UserID        int64   `json:"user_id"`
	IsBan         bool    `json:"is_ban"`
	ServerDisplay *string `json:"server_display"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	Display      string    `json:"display"`
	PasswordHash string    `json:"password_hash"`
	JoinedAt     time.Time `json:"joined_at"`
	IsDeleted    bool      `json:"is_deleted"`
	CookieVer    int64     `json:"cookie_ver"`
}
