// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package query

import (
	"context"
	"database/sql"
)

const createMembership = `-- name: CreateMembership :exec
INSERT INTO server_members(user_id, server_id) VALUES (?, ?)
`

type CreateMembershipParams struct {
	UserID   int64
	ServerID int64
}

// MEMBERSHIP
func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.ExecContext(ctx, createMembership, arg.UserID, arg.ServerID)
	return err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages(id, server_id, user_id, content, reply_to, is_reply)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID       int64
	ServerID int64
	UserID   int64
	Content  string
	ReplyTo  sql.NullInt64
	IsReply  bool
}

// MESSAGES
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.ServerID,
		arg.UserID,
		arg.Content,
		arg.ReplyTo,
		arg.IsReply,
	)
	return err
}

const createReaction = `-- name: CreateReaction :exec
INSERT INTO message_reactions(message_id, user_id, emoji) VALUES (?, ?, ?)
`

type CreateReactionParams struct {
	MessageID int64
	UserID    int64
	Emoji     string
}

// REACTIONS
func (q *Queries) CreateReaction(ctx context.Context, arg CreateReactionParams) error {
	_, err := q.db.ExecContext(ctx, createReaction, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}

const createServer = `-- name: CreateServer :exec
INSERT INTO servers(id, name, owner) VALUES (?, ?, ?)
`

type CreateServerParams struct {
	ID    int64
	Name  string
	Owner int64
}

// SERVERS
func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) error {
	_, err := q.db.ExecContext(ctx, createServer, arg.ID, arg.Name, arg.Owner)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users(id, username, display, password_hash) VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           int64
	Username     string
	Display      string
	PasswordHash string
}

// USERS
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Display,
		arg.PasswordHash,
	)
	return err
}

const deleteExpiredInvites = `-- name: DeleteExpiredInvites :exec
DELETE FROM server_invites WHERE expires_at <= datetime('now')
`

// INVITES
// Run this periodically to delete expired invites
func (q *Queries) DeleteExpiredInvites(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredInvites)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM server_invites WHERE id = ?
`

func (q *Queries) DeleteInvite(ctx context.Context, id interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteInvite, id)
	return err
}

const deleteMessage = `-- name: DeleteMessage :execrows
DELETE FROM messages
WHERE
  messages.id = ?1
  AND (user_id = ?2 OR server_id IN (SELECT id FROM servers WHERE owner = ?2))
`

type DeleteMessageParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMessage, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteReaction = `-- name: DeleteReaction :execrows
DELETE FROM message_reactions WHERE message_id = ? AND user_id = ? AND emoji = ?
`

type DeleteReactionParams struct {
	MessageID int64
	UserID    int64
	Emoji     string
}

func (q *Queries) DeleteReaction(ctx context.Context, arg DeleteReactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReaction, arg.MessageID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers WHERE id = ?
`

func (q *Queries) DeleteServer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteServer, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET
  username = 'Deleted User ' || id,
  display = 'Deleted User ' || id,
  password_hash = '',
  is_deleted = 1
WHERE
  id = ?
  AND is_deleted = 0
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const editMessage = `-- name: EditMessage :exec
UPDATE messages SET content = ?, is_edited = 1 WHERE id = ?
`

type EditMessageParams struct {
	Content string
	ID      int64
}

func (q *Queries) EditMessage(ctx context.Context, arg EditMessageParams) error {
	_, err := q.db.ExecContext(ctx, editMessage, arg.Content, arg.ID)
	return err
}

const getInvite = `-- name: GetInvite :one
SELECT id, server_id, user_id, expires_at FROM server_invites WHERE id = ?
`

func (q *Queries) GetInvite(ctx context.Context, id interface{}) (ServerInvite, error) {
	row := q.db.QueryRowContext(ctx, getInvite, id)
	var i ServerInvite
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.ExpiresAt,
	)
	return i, err
}

const getMessageReactions = `-- name: GetMessageReactions :many
SELECT message_id, user_id, emoji FROM message_reactions WHERE message_id = ?
`

func (q *Queries) GetMessageReactions(ctx context.Context, messageID int64) ([]MessageReaction, error) {
	rows, err := q.db.QueryContext(ctx, getMessageReactions, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageReaction
	for rows.Next() {
		var i MessageReaction
		if err := rows.Scan(&i.MessageID, &i.UserID, &i.Emoji); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerMemberCount = `-- name: GetServerMemberCount :one
SELECT COUNT(*) FROM server_members WHERE server_id = ?
`

func (q *Queries) GetServerMemberCount(ctx context.Context, serverID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getServerMemberCount, serverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getServerMembers = `-- name: GetServerMembers :many
SELECT server_id, user_id, is_ban, server_display FROM server_members WHERE server_id = ? LIMIT ? OFFSET ?
`

type GetServerMembersParams struct {
	ServerID int64
	Limit    int64
	Offset   int64
}

func (q *Queries) GetServerMembers(ctx context.Context, arg GetServerMembersParams) ([]ServerMember, error) {
	rows, err := q.db.QueryContext(ctx, getServerMembers, arg.ServerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServerMember
	for rows.Next() {
		var i ServerMember
		if err := rows.Scan(
			&i.ServerID,
			&i.UserID,
			&i.IsBan,
			&i.ServerDisplay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerMessage = `-- name: GetServerMessage :one
SELECT id, server_id, user_id, content, reply_to, is_reply, is_edited, time FROM messages WHERE server_id = ? AND id = ?
`

type GetServerMessageParams struct {
	ServerID int64
	ID       int64
}

func (q *Queries) GetServerMessage(ctx context.Context, arg GetServerMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, getServerMessage, arg.ServerID, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.Content,
		&i.ReplyTo,
		&i.IsReply,
		&i.IsEdited,
		&i.Time,
	)
	return i, err
}

const getServerMessages = `-- name: GetServerMessages :many
SELECT id, server_id, user_id, content, reply_to, is_reply, is_edited, time FROM messages WHERE server_id = ? ORDER BY id LIMIT ? OFFSET ?
`

type GetServerMessagesParams struct {
	ServerID int64
	Limit    int64
	Offset   int64
}

func (q *Queries) GetServerMessages(ctx context.Context, arg GetServerMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getServerMessages, arg.ServerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.UserID,
			&i.Content,
			&i.ReplyTo,
			&i.IsReply,
			&i.IsEdited,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display, password_hash, joined_at, is_deleted, cookie_ver FROM users WHERE username = ? AND is_deleted = 0
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Display,
		&i.PasswordHash,
		&i.JoinedAt,
		&i.IsDeleted,
		&i.CookieVer,
	)
	return i, err
}

const getUserServersIDs = `-- name: GetUserServersIDs :many
SELECT server_id FROM server_members WHERE user_id = ?
`

func (q *Queries) GetUserServersIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getUserServersIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var server_id int64
		if err := rows.Scan(&server_id); err != nil {
			return nil, err
		}
		items = append(items, server_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinServer = `-- name: JoinServer :exec
INSERT INTO server_members(user_id, server_id) VALUES (?, ?)
`

type JoinServerParams struct {
	UserID   int64
	ServerID int64
}

func (q *Queries) JoinServer(ctx context.Context, arg JoinServerParams) error {
	_, err := q.db.ExecContext(ctx, joinServer, arg.UserID, arg.ServerID)
	return err
}

const leaveServer = `-- name: LeaveServer :exec
DELETE FROM server_members WHERE user_id = ? AND server_id = ? and is_ban = 0
`

type LeaveServerParams struct {
	UserID   int64
	ServerID int64
}

func (q *Queries) LeaveServer(ctx context.Context, arg LeaveServerParams) error {
	_, err := q.db.ExecContext(ctx, leaveServer, arg.UserID, arg.ServerID)
	return err
}

const userInServer = `-- name: UserInServer :one
SELECT EXISTS (SELECT 1 FROM server_members WHERE user_id = ? AND server_id = ?)
`

type UserInServerParams struct {
	UserID   int64
	ServerID int64
}

func (q *Queries) UserInServer(ctx context.Context, arg UserInServerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userInServer, arg.UserID, arg.ServerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
